# Generated by Django 4.0.4 on 2022-05-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('query_result', models.JSONField()),
                ('query_time', models.CharField(max_length=6)),
                ('query_success', models.BooleanField(default=False)),
                ('location_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.locations')),
                ('user_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
