# Generated by Django 4.0.4 on 2022-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
